---
- name: Helm install cloudpg repo
  command: helm repo add {{ item.name }} {{ item.url }}
  with_items: "{{ repos }}"

- name: write values template
  copy:
    content: |
      {{ values_file }}
    dest: /tmp/values_{{ name }}-template.txt
    mode: 0777
  when: ( values_file != "" ) and ( values_url == "" )

- name: compile values
  template:
    src: /tmp/values_{{ name }}-template.txt
    dest: /tmp/values_{{ name }}.yml
    #remote_src: true
  when: ( values_file != "" ) and ( values_url == "" )

- name: get values from url
  get_url:
      url: "{{ values_url }}"
      dest: "/tmp/values_{{ name }}.yml"
  when: ( values_url != "" ) and ( values_file == "" )

- name: Helm3 install chart {{ chart }}
  command: "helm --kubeconfig {{ kubeconfig_path }} install {{ name }} -f /tmp/values_{{ name }}.yml {{ chart }} {{ inline_options }}"
  when: (( values_url != "" ) or ( values_file != "" )) and ( helm_version == "v3" )

- name: Helm3 install chart {{ chart }}
  command: "helm --kubeconfig {{ kubeconfig_path }} install {{ name }} {{ chart }} {{ inline_options }}"
  when: (( values_url == "" ) and ( values_file == "" )) and ( helm_version == "v3" )

- name: Helm2 install chart {{ chart }}
  command: "helm --kubeconfig {{ kubeconfig_path }} install --name {{ name }} -f /tmp/values_{{ name }}.yml {{ chart }} {{ inline_options }}"
  when: (( values_url != "" ) or ( values_file != "" )) and ( helm_version == "v2" )

- name: Helm2 install chart {{ chart }}
  command: "helm --kubeconfig {{ kubeconfig_path }} install --name {{ name }} {{ chart }} {{ inline_options }}"
  when: (( values_url == "" ) and ( values_file == "" )) and ( helm_version == "v2" )
