---
- name: Helm install cloudpg repo
  command: helm repo add {{ item.name }} {{ item.url }}
  with_items: "{{ repos }}"

- name: write values "{{ values_file }}"
  copy:
    content: |
      {{ values_file }}
    dest:  /tmp/values_{{ name }}-template.txt

- name: compile values
  template:
    src:  /tmp/values_{{ name }}-template.txt
    dest: /tmp/values_{{ name }}.yml

- name: Helm install chart {{ chart }}
  command: "helm install --name {{ name }} -f /tmp/values_{{ name }}.yml {{ chart }}"
